# Generated by Django 5.1.6 on 2025-03-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth_bru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_logo', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='AccountProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_datetime_sync_bru', models.DateTimeField(auto_now=True, verbose_name='Дата последней синхронизации')),
                ('json_settings', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_providers', to='oauth_bru.account')),
            ],
            options={
                'db_table': 'accounts_providers',
            },
        ),
    ]
