# Generated by Django 5.1.6 on 2025-03-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_settings', '0001_initial'),
        ('messages_proccessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprovider',
            name='default_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messages_proccessing.providerchannel'),
        ),
        migrations.AddField(
            model_name='accountprovider',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='account_settings.provider'),
        ),
    ]
