# Generated by Django 5.1.6 on 2025-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, unique=True)),
                ('app_id', models.IntegerField()),
                ('secret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
