# Generated by Django 5.1.6 on 2025-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BruWhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('employee_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('whook_id', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sms_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('social_type', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bru_whooks',
            },
        ),
    ]
