# Generated by Django 5.1.6 on 2025-03-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('WhatsApp', 'Whatsapp'), ('Cascade', 'Cascade'), ('Viber', 'Viber'), ('SMS', 'Sms'), ('VK', 'Vk')])),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='ProviderChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_proccessing.channel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_settings.provider')),
            ],
            options={
                'db_table': 'providers_channels',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('keyword', models.CharField(max_length=255)),
                ('message_len', models.IntegerField()),
                ('condition', models.CharField(choices=[('Строго меньше', 'Lt'), ('Меньше или равно', 'Lte'), ('Равно', 'E'), ('Больше или равно', 'Gte'), ('Строго больше', 'Gt')])),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_keyword_register_sensitive', models.BooleanField(default=False)),
                ('account_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='account_settings.accountprovider')),
                ('provider_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='messages_proccessing.providerchannel')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('account_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account_settings.accountprovider')),
                ('provider_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messages_proccessing.providerchannel')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messages_proccessing.rule')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
